manafoot_home_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ManafootHomeBundle:Default:index }

_index:
    pattern: /contact/
    defaults: { _controller: ManafootHomeBundle:Contact:Index }

_submit:
    pattern: /contact/submit
    defaults: { _controller: ManafootHomeBundle:Contact:Submit }

_index:
    pattern: /
    defaults: { _controller: ManafootHomeBundle:Home:Index }

_login:
    pattern: /login
    defaults: { _controller: ManafootHomeBundle:Login:Login }

_logout:
    pattern: /logout
    defaults: { _controller: ManafootHomeBundle:Login:Logout }

_login_new_user:
    pattern: /login/new
    defaults: { _controller: ManafootHomeBundle:Login:LoginNewUser }

_password_lost:
    pattern: /login/passwordlost
    defaults: { _controller: ManafootHomeBundle:Login:PasswordLost }
