manafoot_game_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ManafootGameBundle:Default:index }

_new_game:
    pattern: /game/new
    defaults: { _controller: ManafootGameBundle:NewGame:NewGame }

resume:
    pattern: /resume/{name}
    defaults: { _controller: ManafootGameBundle:ResumeGame:resume }

continue:
    pattern: /continue
    defaults: { _controller: ManafootGameBundle:ContinueGame:continue }

continue_fast:
    pattern: /continue/fast
    defaults: { _controller: ManafootGameBundle:ContinueGame:continueFast }

fifa:
    pattern: /fifa
    defaults: { _controller: ManafootGameBundle:World:fifa }

fifa_world_cup:
    pattern: /fifa/worldCup
    defaults: { _controller: ManafootGameBundle:World:fifaWorldCup }

fifa_world_cup_edition:
    pattern: /fifa/worldCup/{edition}
    defaults: { _controller: ManafootGameBundle:World:fifaWorldCupEdition }

fifa_concacaf_world_cup_qualification:
    pattern: /fifa/concacaf/worldCupQualification
    defaults: { _controller: ManafootGameBundle:World:fifaConcacafWorldCupQualification }

fifa_concacaf_world_cup_qualification_edition:
    pattern: /fifa/concacaf/worldCupQualification/{edition}
    defaults: { _controller: ManafootGameBundle:World:fifaConcacafWorldCupQualificationEdition }

fifa_conmebol_world_cup_qualification_edition:
    pattern: /fifa/conmebol/worldCupQualification/{edition}
    defaults: { _controller: ManafootGameBundle:World:fifaConmebolWorldCupQualificationEdition }

fifa_uefa_world_cup_qualification_edition:
    pattern: /fifa/uefa/worldCupQualification/{edition}
    defaults: { _controller: ManafootGameBundle:World:fifaUefaWorldCupQualificationEdition }

fifa_caf_world_cup_qualification_edition:
    pattern: /fifa/caf/worldCupQualification/{edition}
    defaults: { _controller: ManafootGameBundle:World:fifaCafWorldCupQualificationEdition }

fifa_afc_world_cup_qualification_edition:
    pattern: /fifa/afc/worldCupQualification/{edition}
    defaults: { _controller: ManafootGameBundle:World:fifaAfcWorldCupQualificationEdition }

fifa_ofc_world_cup_qualification_edition:
    pattern: /fifa/ofc/worldCupQualification/{edition}
    defaults: { _controller: ManafootGameBundle:World:fifaOfcWorldCupQualificationEdition }

fifa_concacaf:
    pattern: /fifa/concacaf
    defaults: { _controller: ManafootGameBundle:World:fifaConcacaf }
